# This is a sample workflow to test or replace with your source code.
#
# This workflow passes the region where the workflow is deployed
# to the Wikipedia API and returns a list of related Wikipedia articles.
# A region is retrieved from the GOOGLE_CLOUD_LOCATION system variable
# unless you input your own search term; for example, {"searchTerm": "asia"}.
main:
    params: [input]
    steps:
    - callCloudRunFunction:
        call: http.get
        args:
            url: 'https://us-central1-stock-index-tracker.cloudfunctions.net/check-stock-index-price'
            headers:
                Authorization: "Bearer {your-bearer-token}"
